name: Initial Setup

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
              python-version: 2.7
      
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone repository
        run: git clone https://github.com/Alikhalkhali/programs-watcher.git

      - name: Execute Python script
        run: |
          cd programs-watcher
          pip3 install -r requirements.txt
          python3 main.py

#      - name: Setup Docker Compose
#        run: |
#          cd programs-watcher
#          docker-compose up -d && python2 main.py
         
