name: Initial Setup

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone repository
        run: git clone https://github.com/Alikhalkhali/programs-watcher.git

      - name: Setup Docker Compose
        run: |
          cd programs-watcher
          touch test.log
          docker-compose up -d && python main.py >> all_logs.log 2>&1 || tee test.log
          cat test.log
         
