name: Initial Setup

on:
  push:
    branches:
      - main

jobs:
  setup:
    runs-on: ubuntu-latest

    steps:

      - name: Set up Python 2
        uses: actions/setup-python@v2
        with:
          python-version: 2.7

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Clone repository
        run: git clone https://github.com/Alikhalkhali/programs-watcher.git

      - name: Setup Docker Compose
        run: |
          cd programs-watcher
          docker-compose up -d && python2 main.py
         
