name: Periodic Execution

on:
  schedule:
    - cron: '*/30 * * * *'

jobs:
  execute-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Execute Python script
        run: |
          cd programs-watcher
          python main.py >> all_logs.log 2>&1
